version: '3'

services:
  db:
    image: mysql:5.7 # 컨테이너 이미지 docker file로 쓸 수 있음
    restart: always # 서버 유지를 위해서 끊김 없이 동작하게 함
    volumes:
      - /data/mysql:/var/lib/mysql #host pc : cotainer 내부 명령
    env_file:
      - .env_db # 파일로 넣을 수도 있다.
    ports:
      - 3308:3306 # -p option과 동일하다
